name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        working-directory: ./linux
        run: make amd64-image
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push docker.io/intergralgmbh/observability-agent:latest

  build-arm64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        working-directory: ./linux
        run: sudo make arm64-image
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push docker.io/intergralgmbh/observability-agent:latest