name: Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        working-directory: ./linux
        run: make amd64-image
  build-ppc64le:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        working-directory: ./linux
        run: sudo make ppc64le-image
  build-arm64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        working-directory: ./linux
        run: sudo make arm64-image